2025-06-22 11:46:35,631 - VocabMaster - INFO - 启动VocabMaster
2025-06-22 11:46:35,633 - VocabMaster - INFO - 使用GUI模式
2025-06-22 11:46:36,114 - VocabMaster - ERROR - 程序运行出错
Traceback (most recent call last):
  File "/Users/liuzhehong/projects/my_projects/vocabmaster/app.py", line 135, in main
    from gui import main
  File "/Users/liuzhehong/projects/my_projects/vocabmaster/gui.py", line 24, in <module>
    from utils.config_gui import show_config_dialog
  File "/Users/liuzhehong/projects/my_projects/vocabmaster/utils/config_gui.py", line 608
    QMessageBox.information(self, "成功", "配置已成功保存！")
IndentationError: unexpected indent
2025-06-22 11:46:36,115 - VocabMaster - ERROR - 未捕获的异常:
Traceback (most recent call last):
  File "/Users/liuzhehong/projects/my_projects/vocabmaster/app.py", line 142, in <module>
    main()
  File "/Users/liuzhehong/projects/my_projects/vocabmaster/app.py", line 135, in main
    from gui import main
  File "/Users/liuzhehong/projects/my_projects/vocabmaster/gui.py", line 24, in <module>
    from utils.config_gui import show_config_dialog
  File "/Users/liuzhehong/projects/my_projects/vocabmaster/utils/config_gui.py", line 608
    QMessageBox.information(self, "成功", "配置已成功保存！")
IndentationError: unexpected indent

